### PR TITLE
Option to use Shizuku instead of an input method

### PR DESCRIPTION
**Pull request by zacharee**
The only way to get Shizuku permissions right now is through the intro slider. I also haven't added in any permission result callbacks, and most of the rest of the UI doesn't adapt to having Shizuku access.

Shizuku also needs at least API 23 (and the hidden API blacklist bypass needs API 19), which is a pretty significant change from 17.

### CODE REVIEW

**Comment by sds100** [comment]
Yeah, can't you keep the min api at 17 and then just check in the code if the device is at least API 23? e.g
`if (Build.VERSION.SDK_INT >= Build.VERSION.M) ....`

**Comment by zacharee** [comment]
Android Studio won't let you build if a module has a lower minSdkVersion than any of its dependencies.

There might be a way to force it to build and use an API check, but I'm not sure.

**Comment by sds100** [comment]
ohhh okay.

**Comment by sds100** [comment]
the restriction bypass library seems to cause it. do we need to use it or is there another way to achieve the same thing?

**Comment by zacharee** [comment]
The Shizuku API minSdkVersion is 23 (https://github.com/RikkaApps/Shizuku-API/blob/dfdd3787f1e5d5e4feaada50707b47654b06179a/manifest.gradle).

Looks like you can use `<uses-sdk tools:overrideLibrary="com.example.android" />` in the KeyMapper manifest to ignore a specific library's minSdkVersion.

So I guess something like:
```
<manifest ...>
...
<uses-sdk tools:overrideLibrary="rikka.shizuku.api, org.chickenhook.restrictionbypass" />
...
</manifest>

And then just do an API 23 check when referencing Shizuku.

**Comment by sds100** [comment]
how did you get it to build? i get `unresolved reference: IInputManager`

**Comment by zacharee** [comment]
I use a specially-compiled SDK JAR to expose hidden APIs.

https://drive.google.com/drive/folders/17oMwQ0xBcSGn159mgbqxcXXEcneUmnph

I can also replace it with reflection access.

**Comment by sds100** [comment]
can you use reflection instead otherwise I can't do CI builds and release to fdroid. thanks

**Comment by zacharee** [comment]
It's using reflection now. I wasn't able to test to make sure I did the reflection right, so just make sure it doesn't crash.

**Comment by sds100** [comment]
cool, will take a look.

**Comment by sds100** [comment]
`Unresolved reference: INJECT_INPUT_EVENT_MODE_WAIT_FOR_FINISH` can you figure out what the value of the constant is and substitute it in ActionPerformerDelegate because it doesn't build.

**Comment by zacharee** [comment]
Replaced.

**Comment by sds100** [comment]
can you add this comment above the method call. `// 2 = InputManager.INJECT_INPUT_EVENT_MODE_WAIT_FOR_FINISH`

**Comment by zacharee** [comment]
Done.

**Comment by sds100** [comment]
cool, it builds!

**Comment by zacharee** [comment]
I added the changes needed to bring the minSdkVersion back to 17. The hidden API bypass thing tries to run automatically, but it shouldn't be an issue since it catches all Exceptions (https://github.com/ChickenHook/RestrictionBypass/blob/master/restrictionbypass/src/main/java/org/chickenhook/restrictionbypass/BypassProvider.java#L52).

**Comment by sds100** [comment]
Ah, cool. Thanks! Could you remove your updates to the libraries and the data store stuff. I'd like to only merge stuff to do with shizuku.

**Comment by sds100** [comment]
Thanks. oh wow, i didnt realise i can work on the same code in the pull request. sweet

**Comment by sds100** [comment]
### TODO
- [ ] check if device is at least API 23 before doing anything related to Shizuku
- [ ] add a setting to use Shizuku instead of an input method
- [ ] ask in the app intro if the user wants to use Shizuku or an input method. Have two buttons which when clicked show a dialog offering multiple ways to install Key Mapper GUI Keyboard and Shizuku.
- [ ] status at top of home screen should change if using shizuku.
- [ ] action errors should change if using shizuku.
- [ ] dont show GUI keyboard ad if using shizuku.

**Comment by sds100** [comment]
Do you think its better to have one setting to make Key Mapper use shizuku when possible or have a setting for each thing Shizuku can be used for?

**Comment by zacharee** [comment]
I think a single option to use Shizuku for everything it can be used for makes more sense.

**Comment by sds100** [comment]
I'm now tracking this request here #746. This pull request prompted me to rewrite the app which means this code is no longer compatible. 😆

**Pull request closed without merging**
