### PR TITLE
WIP: feat (action): add play notification

### LINKED ISSUE #652: Add action to play some sound
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name. => origin/feature/652-play-sound-action
- [x] write tests before working on feature. put issue number in comment
- [x] update documentation
  - Explain the behaviour in Notes
- [x] let translators in Discord server know there are strings to translate
- [x] squash and merge
- [x] delete branch
- [x] update library credits

**Notes**
- [x] use Accessibility stream?
- [x] only enable accessibility stream if a key map that requires it is enabled and the mappings are unpaused
- [x] copy file to Key Mapper's private folder??
- [x] create SoundsManager that
  - has method for saving sounds
  - method for retrieving sounds
  - ~~Automatically store hashes of new files and don't save duplicates of files.~~
    - ~~create separate data store to preferences~~
    - ~~the hashes should not be saved with the back ups~~
```
MessageDigest digest = MessageDigest.getInstance("SHA-256");
byte[] hash = digest.digest(text.getBytes(StandardCharsets.UTF_8));
```
- [x] back up sound files with key maps?? use zip4j to back up to a zip file https://github.com/srikanth-lingala/zip4j
- [x] automatically use the sound files name
- [x] show an option when creating sounds to select an existing sound or a new one.
- [x] ~~store file hash in action~~
- [x] do restoring
- [x] ensure back ups without being in a zip folder are still supported
- [x] show error if failed to create sound action
- [x] show action error if sound doesnt exist
- [x] always back up all sounds incase the user wants to save a sound for later. Show a button to delete sounds in the settings.
- [x] ~~automatically delete sounds when they aren't needed by key maps any more.~~ The user might want to use a sound later.
- [x] stop playing when key maps are paused
- [x] do TODO items

My use case would be to have a virtual bike bell.

Goal is to use one of those:
image
which is just a one button bluetooth keyboard that sends vol-up keycode.

and make my EUC bell when I click the button

EUC is that:
image

The EUC can connect to android phone as a a2dp speaker, so the only thing remaining is to map the bluetooth keyboard to playing a sounds. I guess KeyMapper is the nearest thing available to do that.
I already recognise the bluetooth button, but it is missing a play sound feature.
The play media is for me not an option as it would require changing the current music with a honk sound before the ride. pretty impractical.

### PR DESCRIPTION
**Pull request by tardyp**
This my evening hack attempt (including installing Android Studio) to fix #652

I am not exactly sure yet how to pass a parameter to a system action (that would be the actual URL of the notification)

I would welcome any advice on that.

### CODE REVIEW

**Comment by sds100** [comment]
I'm sorry but I just merged my complete rewrite of Key Mapper so this makes your code completely incompatible right now. I will probably add a way for you to pick the sound file that you want to play.

**Comment by tardyp** [comment]
@sds100 Thanks for the heads-up! I now see your develop branch

I think the notification API is actually better (for my use case) as it reduces the main media, so we can play music while still be capable of having our virtual horn/bell.

I also wanted to ba capable for that use case of forcing the notification sound level and switching out of silent/vibration mode if necessary.

**Comment by sds100** [comment]
Ah, so you want to play the default notification sound? There are already actions to change the notification volume and switching between silent/vibrate mode.

**Comment by tardyp** [comment]
No I want to play a notification sound specific to this key (and put the volume at maximum)
Indeed, maybe we can put several actions.

Ideally I'd like to implement the algorithme:

```java
old_volume = get_notification_volume() 
old_notification_mode = get_notification_mode()
set_notification_volume(action.forced_notification_volume)
set_notification_mode(SOUND)
play_notification(action.notification_url)
set_notification_volume(old_volume)
set_notification_mode(old_notification_mode)
```

**Comment by sds100** [comment]
It looks like you just want to play a sound right?  I'm trying to find a more generic solution to the problem so would an action to "play a sound" which then allows you to pick the sound file suffice? There is already an action to set the volume so you can use that as a 2nd action. Does it have to play out of the notification stream or the media stream?

**Comment by tardyp** [comment]
So indeed, it would be nice to be able to choice the media or notification stream, not sure if it is possible to play arbitrary sound in notification stream.

What I tried to capture in the previous comment is the need to restore the previous state. I don't think it is currently possible.

- Play the sound at maximum volume
- Then restore the phone volume or vibration mode.

**Comment by sds100** [comment]
Okay, how come you want to play through the notification stream? Would the media stream be okay? Yeah, restoring the state wouldn't be possible right now but if it is played in the media stream you will only need to set the media stream volume to whatever you want before the sound plays. Would you also want the media stream volume to reset to the value it was at before?

**Comment by tardyp** [comment]
yes the goal would be to play the bell as loud as possible, but without impacting the normal settings.

**Comment by sds100** [comment]
I should be able to use the Accessibility stream instead of the notification or media stream. That seems perfect for the job because it is separate from notifications AND media

**Comment by tardyp** [comment]
Cool!
I've been a little less active on my branch this because the bluetooth keyboard events just won't wake up the phone if it is in the pocket, which is the whole point of the usecase.

Basically, the notification works for some time after screen off, but then will not anymore after a while..
its on pixel4a

**Comment by sds100** [comment]
I am working on this feature my self

**Comment by sds100** [comment]
Lets discuss in the issue #652

**Pull request closed without merging**
